SMOOTHING_ALPHA = 0.6

DETECTION_CONFIDENCE = 0.7
TRACKING_CONFIDENCE = 0.7
MAX_NUM_HANDS = 1

ANGLE_THRESHOLD_CLICK = 50
ANGLE_THRESHOLD_STRAIGHT = 90
THUMB_INDEX_DIST_CLICK = 0.06

SCREENSHOT_COOLDOWN = 1.0
SAVE_DIR = "Screenshots"

WEBCAM_WIDTH = 640
WEBCAM_HEIGHT = 480

CLICK_DEBOUNCE = 0.25
DRAG_DEBOUNCE = 0.15
MODEL_COMPLEXITY = 0
